bets_dash/urls.py
from django.urls import path, include

from . import views

app_name = "bets_dash"

urlpatterns = [
    path("", views.index, name="index"),
]

bets_input/urls.py
from django.urls import path

from . import views

app_name = 'bets_input'

urlpatterns = [
    path('', views.index, name='index'),
    path('bets_input/ordering/', views.ordering, name='ordering'),
    path('sort/', views.sort, name='sort'),
    path('bets_input/', views.bets_input, name='bets_input'),
]

f1_dashboard_tips_input/urls.py
from django.contrib import admin
from django.urls import path, include
from tips_input.dash_app import dash_app

urlpatterns = [
    path("admin/", admin.site.urls),
    path('tips/', include('tips_input.urls')),
    path('dash/', include('tips_dash.urls')),
    # this is needed for dash to work
    path('', include('django_plotly_dash.urls')),
]

formula1_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.db.utils import OperationalError, ProgrammingError
from django.core.exceptions import ObjectDoesNotExist

# weird error that happens when performing migrate (completely unrelated to the Dash plugin)
try:
    from bets_dash.dash_app import dash_app
except OperationalError as err:
    print(f"Probably a false error, but here it goes: \n {err}")
except IndexError as err:
    print(f"Probably a false error, but here it goes: \n {err}")
except ObjectDoesNotExist as err:
    print(f"Probably a false error, but here it goes: \n {err}")
except ProgrammingError as err:
    print(f"Probably a false error, but here it goes: \n {err}")
except AttributeError as err:
    print(f"Probably a false error, but here it goes: \n {err}")


urlpatterns = [
    # this is needed for dash to work
    path("", include("django_plotly_dash.urls")),
    path("admin/", admin.site.urls),
    path("", include("bets_input.urls")),
    path("dash/", include("bets_dash.urls")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bets_input/style.css' %}">

    <!-- jQuery and Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

	<title>{% block title %}F1 Dashboard bets{% endblock %}</title>
	<style>
		.asteriskField {
			display: none;
		}
	</style>
</head>
<body>
    <header class="d-flex py-3 bg-dark text-white" style="display:flex;justify-content: space-around;">
        <picture>
            <source srcset="/static/bets_input/formula-1-logo-7.png">
            <img src="/static/bets_input/formula-1-logo-7.png" alt="Flowers" class="img-fluid" style="max-width: 150px">
        </picture>
        <ul class="nav nav-pills">
            {% if request.get_full_path == '/' or request.get_full_path == '/bets_input/ordering/' or request.get_full_path == '/bets_input/' %}
                <li class="nav-item">
                    <a class="nav-link bg-secondary active" href={% url 'bets_input:index' %}>Bets registration</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href={% url 'bets_dash:index' %}>Result dashboard</a>
                </li>
            {% elif request.get_full_path == '/dash/' %}
                <li class="nav-item">
                    <a class="nav-link text-white" href={% url 'bets_input:index' %}>Bets registration</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link bg-secondary active" href={% url 'bets_dash:index' %}>Result dashboard</a>
                </li>
            {% endif %}
        </ul>
    </header>
    {% block base %}
	{% endblock %}
	<script>
        htmx.onLoad(function(content) {
            var sortables = content.querySelectorAll(".sortable");
            for (var i = 0; i < sortables.length; i++) {
                var sortable = sortables[i];
                new Sortable(sortable, {
                    animation: 150,
                    ghostClass: 'blue-background-class'
                });
            }
        })
    </script>
</body>
</html>

templates/base_dash.html
{% extends 'base.html' %}

{% block base %}
    <div class="container-wide mb-1">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

templates/base_input.html
{% extends 'base.html' %}

{% block base %}
    <br>
    <br>
    <div class="container mb-4">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

templates/bets_index.html
{% extends 'base_input.html' %}
{% load crispy_forms_tags %}

{% block content %}
   {% crispy form %}

{% load plotly_dash %}

{% endblock %}

templates/betting_after_start.html
{% extends 'base_input.html' %}

{% block content %}
    <div class="alert alert-danger" role="alert" style="align-items: center">
        <h3 style="text-align: center">Sorry, this event has already started. You cannot change your bets anymore.</h3>
    </div>
    <input class="btn btn-outline-secondary btn-lg btn-block" type=button value="Go back" onClick="javascript:history.go(-1);">
{% endblock %}

templates/dash_index.html
{% extends 'base_dash.html' %}

{% block content %}

{% load plotly_dash %}

{% plotly_app_bootstrap name="MainDashApp" aspect="21by9" %}
{% endblock %}

templates/extras_input.html
{% extends 'base_input.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{% endblock %}

templates/ordering.html
{% extends 'base_input.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if race_type == 'quali' %}
        <h2 class="alert alert-dark" style="text-align: center">Expected results (quali)</h2>
    {% endif %}
    {% if race_type == 'race' %}
        <h2 class="alert alert-dark" style="text-align: center">Expected results (race)</h2>
    {% endif %}
    {% if race_type == 'sprint' %}
        <h2 class="alert alert-dark" style="text-align: center">Expected results (sprint)</h2>
    {% endif %}
    <div class="align-center">
        <main class="d-flex">
            <section id="drivers-list" class="col-12">
                {% include 'sortable_drivers.html' %}
            </section>
        </main>
    </div>
{% endblock content %}

templates/sortable_drivers.html
<section class="col-6">
<form class="sortable list-group " hx-trigger="end" hx-post={% url 'bets_input:sort' %} hx-target="#drivers-list" >
    {% csrf_token %}
    <div class="htmx-indicator">Updating...</div>
        {% for bet in bets %}
            <div class="mb-1">
                <input type='hidden' name='driver_order' value={{ bet.driver.pk }} />

                <li class="list-group-item d-flex justify-content-between align-items-center {{ bet.driver.team.lc_name }}">
                    {% if race_type == 'quali' %}
                        P{{ bet.position_quali }} {{ bet.driver.name }} ({{ bet.driver.team }})
                    {% endif %}
                    {% if race_type == 'race' %}
                        P{{ bet.position }} {{ bet.driver.name }} ({{ bet.driver.team }})
                    {% endif %}
                    {% if race_type == 'sprint' %}
                        P{{ bet.position_sprint }} {{ bet.driver.name }} ({{ bet.driver.team }})
                    {% endif %}
                </li>
            </div>
        {% endfor %}
        <input type='hidden' name='current_player' value={{ current_player }} />
        <input type='hidden' name='current_race' value={{ current_race }} />
        <input type='hidden' name='race_type' value={{ race_type }} />
</form>
</section>

templates/sprint_not_allowed.html
{% extends 'base_input.html' %}

{% block content %}
    <div class="alert alert-danger" role="alert" style="align-items: center">
        <h3 style="text-align: center">Sorry, this race is not a sprint race. Here are all the sprint races:</h3>
    </div>
    <div class="alert alert-secondary" role="secondary">
    {% for race in sprints %}
        <h4 style="text-align: center">
            {{ race.name }}, {{ race.country }} @ {{ race.datetime_of_race_gmt }} (GMT)
        </h4>
        {% if not forloop.last %}
            <br>
        {% endif %}
    {% endfor %}
    </div>
    <br>
    <input class="btn btn-outline-secondary btn-lg btn-block" type=button value="Go back" onClick="javascript:history.go(-1);">
{% endblock %}